### PR TITLE
Failure in master

### PR DESCRIPTION
**Pull request by szepeviktor**
Could you merge this one?
https://github.com/cloudflare/semver_bash/pull/10/files

### CODE REVIEW

**Comment by szepeviktor** [comment]
@martinhbramwell Please merge that PR.

**Comment by martinhbramwell** [comment]
I'm not sure how to merge as you expect.  You are asking me to pull from your fork of my repo, but the PR shows only a (spurious?) change to the README.  All the other changes are to your fork of [the cloudflare repo](https://github.com/cloudflare/semver_bash). I suppose I could somehow pull those, but the history might look kind of screwy.

**Comment by szepeviktor** [comment]
OK-OK.

Creating a *real* PR....

**Comment by szepeviktor** [comment]
Meanwhile I've realized: **We have a failure in master**

```
Special section vs no special comparisons

semverEQ R1.3.2 R1.3.2a: passed
semverLT R1.3.2 R1.3.2a: FAILED, expected '1', actual: '0'
semverGT R1.3.2 R1.3.2a: FAILED, expected '0', actual: '1'
semverEQ R1.3.2a R1.3.2: passed
semverLT R1.3.2a R1.3.2: FAILED, expected '0', actual: '1'
semverGT R1.3.2a R1.3.2: FAILED, expected '1', actual: '0'
```

**Comment by szepeviktor** [comment]
@martinhbramwell https://github.com/warehouseman/semver_bash/commit/376dad83a2eead182d0544db768628bba52275f1 broke the tests.

**Comment by szepeviktor** [comment]
@martinhbramwell Could you fix the tests and `exit 1` on failure?

**Comment by martinhbramwell** [comment]
I don't really understand what you want me to do?  Can you not provide a PR?

**Comment by szepeviktor** [comment]
Two things:

https://github.com/warehouseman/semver_bash/commit/376dad83a2eead182d0544db768628bba52275f1 broke the tests. Please run the tests and you'll see!

Travis to be effective it is necessary to have proper exit status: 0 on OK, 1 on failure. This needs to be implemented in the test script.

**Comment by martinhbramwell** [comment]
Is there any chance you could do that and send me a PR?

Please.

**Comment by szepeviktor** [comment]
Sorry, no.

**Pull request closed without merging**
